export function normalizeState(state) {
    if (!state) return state;
    return stateMapping[state.toUpperCase()] || state;
  }
  

const stateMapping = {
    // Estados Unidos
    "AL": "ALABAMA", "ALABAMA": "ALABAMA", "Alabama": "ALABAMA", "al": "ALABAMA",
    "AK": "ALASKA", "ALASKA": "ALASKA", "Alaska": "ALASKA",
    "AZ": "ARIZONA", "ARIZONA": "ARIZONA", "Arizona": "ARIZONA", "Az": "ARIZONA",
    "AR": "ARKANSAS", "ARKANSAS": "ARKANSAS", "Arkansas": "ARKANSAS", "Ar": "ARKANSAS",
    "CA": "CALIFORNIA", "CALIFORNIA": "CALIFORNIA", "California": "CALIFORNIA", "Ca": "CALIFORNIA", "ca": "CALIFORNIA",
    "CO": "COLORADO", "COLORADO": "COLORADO", "Colorado": "COLORADO", "Co": "COLORADO", "co": "COLORADO",
    "CT": "CONNECTICUT", "CONNECTICUT": "CONNECTICUT", "Connecticut": "CONNECTICUT", "Ct": "CONNECTICUT", "ct": "CONNECTICUT",
    "DE": "DELAWARE", "DELAWARE": "DELAWARE", "Delaware": "DELAWARE", "De": "DELAWARE", "de": "DELAWARE",
    "FL": "FLORIDA", "FLORIDA": "FLORIDA", "Florida": "FLORIDA", "Fl": "FLORIDA", "fl": "FLORIDA",
    "GA": "GEORGIA", "GEORGIA": "GEORGIA", "Georgia": "GEORGIA", "Ga": "GEORGIA", "ga": "GEORGIA",
    "HI": "HAWAII", "HAWAII": "HAWAII", "Hawaii": "HAWAII",
    "ID": "IDAHO", "IDAHO": "IDAHO", "Idaho": "IDAHO", "Id": "IDAHO", "id": "IDAHO",
    "IL": "ILLINOIS", "ILLINOIS": "ILLINOIS", "Illinois": "ILLINOIS", "Il": "ILLINOIS", "il": "ILLINOIS",
    "IN": "INDIANA", "INDIANA": "INDIANA", "Indiana": "INDIANA", "In": "INDIANA", "in": "INDIANA",
    "IA": "IOWA", "IOWA": "IOWA", "Iowa": "IOWA", "Ia": "IOWA", "ia": "IOWA",
    "KS": "KANSAS", "KANSAS": "KANSAS", "Kansas": "KANSAS", "Ks": "KANSAS", "ks": "KANSAS",
    "KY": "KENTUCKY", "KENTUCKY": "KENTUCKY", "Kentucky": "KENTUCKY", "Ky": "KENTUCKY", "ky": "KENTUCKY",
    "LA": "LOUISIANA", "LOUISIANA": "LOUISIANA", "Louisiana": "LOUISIANA", "La": "LOUISIANA", "la": "LOUISIANA",
    "ME": "MAINE", "MAINE": "MAINE", "Maine": "MAINE", "Me": "MAINE", "me": "MAINE",
    "MD": "MARYLAND", "MARYLAND": "MARYLAND", "Maryland": "MARYLAND", "Md": "MARYLAND", "md": "MARYLAND",
    "MA": "MASSACHUSETTS", "MASSACHUSETTS": "MASSACHUSETTS", "Massachusetts": "MASSACHUSETTS", "Ma": "MASSACHUSETTS", "ma": "MASSACHUSETTS",
    "MI": "MICHIGAN", "MICHIGAN": "MICHIGAN", "Michigan": "MICHIGAN", "Mi": "MICHIGAN", "mi": "MICHIGAN",
    "MN": "MINNESOTA", "MINNESOTA": "MINNESOTA", "Minnesota": "MINNESOTA", "Mn": "MINNESOTA", "mn": "MINNESOTA",
    "MS": "MISSISSIPPI", "MISSISSIPPI": "MISSISSIPPI", "Mississippi": "MISSISSIPPI",
    "MO": "MISSOURI", "MISSOURI": "MISSOURI", "Missouri": "MISSOURI", "Mo": "MISSOURI", "mo": "MISSOURI",
    "MT": "MONTANA", "MONTANA": "MONTANA", "Montana": "MONTANA",
    "NE": "NEBRASKA", "NEBRASKA": "NEBRASKA", "Nebraska": "NEBRASKA", "Ne": "NEBRASKA",
    "NV": "NEVADA", "NEVADA": "NEVADA", "Nevada": "NEVADA", "Nv": "NEVADA",
    "NH": "NEW HAMPSHIRE", "NEW HAMPSHIRE": "NEW HAMPSHIRE", "New Hampshire": "NEW HAMPSHIRE", "Nh": "NEW HAMPSHIRE",
    "NJ": "NEW JERSEY", "NEW JERSEY": "NEW JERSEY", "New Jersey": "NEW JERSEY", "Nj": "NEW JERSEY", "nj": "NEW JERSEY",
    "NM": "NEW MEXICO", "NEW MEXICO": "NEW MEXICO", "New Mexico": "NEW MEXICO",
    "NY": "NEW YORK", "NEW YORK": "NEW YORK", "New York": "NEW YORK", "Ny": "NEW YORK", "ny": "NEW YORK",
    "NC": "NORTH CAROLINA", "NORTH CAROLINA": "NORTH CAROLINA", "North Carolina": "NORTH CAROLINA", "Nc": "NORTH CAROLINA", "nc": "NORTH CAROLINA",
    "ND": "NORTH DAKOTA", "NORTH DAKOTA": "NORTH DAKOTA", "North Dakota": "NORTH DAKOTA",
    "OH": "OHIO", "OHIO": "OHIO", "Ohio": "OHIO", "Oh": "OHIO", "oh": "OHIO",
    "OK": "OKLAHOMA", "OKLAHOMA": "OKLAHOMA", "Oklahoma": "OKLAHOMA", "Ok": "OKLAHOMA", "ok": "OKLAHOMA",
    "OR": "OREGON", "OREGON": "OREGON", "Oregon": "OREGON",
    "PA": "PENNSYLVANIA", "PENNSYLVANIA": "PENNSYLVANIA", "Pennsylvania": "PENNSYLVANIA", "Pa": "PENNSYLVANIA", "pa": "PENNSYLVANIA",
    "RI": "RHODE ISLAND", "RHODE ISLAND": "RHODE ISLAND", "Rhode Island": "RHODE ISLAND", "Ri": "RHODE ISLAND",
    "SC": "SOUTH CAROLINA", "SOUTH CAROLINA": "SOUTH CAROLINA", "South Carolina": "SOUTH CAROLINA", "Sc": "SOUTH CAROLINA", "sc": "SOUTH CAROLINA",
    "SD": "SOUTH DAKOTA", "SOUTH DAKOTA": "SOUTH DAKOTA", "South Dakota": "SOUTH DAKOTA",
    "TN": "TENNESSEE", "TENNESSEE": "TENNESSEE", "Tennessee": "TENNESSEE", "Tn": "TENNESSEE",
    "TX": "TEXAS", "TEXAS": "TEXAS", "Texas": "TEXAS", "Tx": "TEXAS", "tx": "TEXAS",
    "UT": "UTAH", "UTAH": "UTAH", "Utah": "UTAH",
    "VT": "VERMONT", "VERMONT": "VERMONT", "Vermont": "VERMONT",
    "VA": "VIRGINIA", "VIRGINIA": "VIRGINIA", "Virginia": "VIRGINIA", "Va": "VIRGINIA",
    "WA": "WASHINGTON", "WASHINGTON": "WASHINGTON", "Washington": "WASHINGTON", "Wa": "WASHINGTON", "wa": "WASHINGTON",
    "WV": "WEST VIRGINIA", "WEST VIRGINIA": "WEST VIRGINIA", "West Virginia": "WEST VIRGINIA", "Wv": "WEST VIRGINIA", "wv": "WEST VIRGINIA",
    "WI": "WISCONSIN", "WISCONSIN": "WISCONSIN", "Wisconsin": "WISCONSIN", "Wi": "WISCONSIN", "wi": "WISCONSIN",
    "WY": "WYOMING", "WYOMING": "WYOMING", "Wyoming": "WYOMING", "Wy": "WYOMING",
  
    // Canadá
    "AB": "ALBERTA", "ALBERTA": "ALBERTA", "Alberta": "ALBERTA",
    "BC": "BRITISH COLUMBIA", "BRITISH COLUMBIA": "BRITISH COLUMBIA", "British Columbia": "BRITISH COLUMBIA",
    "MB": "MANITOBA", "MANITOBA": "MANITOBA", "Manitoba": "MANITOBA",
    "NB": "NEW BRUNSWICK", "NEW BRUNSWICK": "NEW BRUNSWICK", "New Brunswick": "NEW BRUNSWICK",
    "NL": "NEWFOUNDLAND AND LABRADOR", "NEWFOUNDLAND": "NEWFOUNDLAND AND LABRADOR", "Newfoundland": "NEWFOUNDLAND AND LABRADOR",
    "NS": "NOVA SCOTIA", "NOVA SCOTIA": "NOVA SCOTIA", "Nova Scotia": "NOVA SCOTIA",
    "ON": "ONTARIO", "ONTARIO": "ONTARIO", "Ontario": "ONTARIO",
    "PE": "PRINCE EDWARD ISLAND", "PRINCE EDWARD ISLAND": "PRINCE EDWARD ISLAND", "Prince Edward Island": "PRINCE EDWARD ISLAND",
    "QC": "QUEBEC", "QUEBEC": "QUEBEC", "Quebec": "QUEBEC", "Qu�bec": "QUEBEC",
    "SK": "SASKATCHEWAN", "SASKATCHEWAN": "SASKATCHEWAN", "Saskatchewan": "SASKATCHEWAN",
  
    // México
    "AG": "AGUASCALIENTES", "AGUASCALIENTES": "AGUASCALIENTES", "Aguascalientes": "AGUASCALIENTES",
    "BC": "BAJA CALIFORNIA", "BAJA CALIFORNIA": "BAJA CALIFORNIA", "Baja California": "BAJA CALIFORNIA",
    "BS": "BAJA CALIFORNIA SUR", "BAJA CALIFORNIA SUR": "BAJA CALIFORNIA SUR", "Baja California Sur": "BAJA CALIFORNIA SUR",
    "CH": "CHIHUAHUA", "CHIHUAHUA": "CHIHUAHUA", "Chihuahua": "CHIHUAHUA",
    "CL": "COAHUILA", "COAHUILA": "COAHUILA", "Coahuila": "COAHUILA",
    "CM": "COLIMA", "COLIMA": "COLIMA", "Colima": "COLIMA",
    "CS": "CHIAPAS", "CHIAPAS": "CHIAPAS", "Chiapas": "CHIAPAS",
    "DF": "CIUDAD DE MÉXICO", "CIUDAD DE MÉXICO": "CIUDAD DE MÉXICO", "Ciudad de México": "CIUDAD DE MÉXICO",
    "DG": "DURANGO", "DURANGO": "DURANGO", "Durango": "DURANGO",
    "GT": "GUANAJUATO", "GUANAJUATO": "GUANAJUATO", "Guanajuato": "GUANAJUATO",
    "GR": "GUERRERO", "GUERRERO": "GUERRERO", "Guerrero": "GUERRERO",
    "HG": "HIDALGO", "HIDALGO": "HIDALGO", "Hidalgo": "HIDALGO",
    "JA": "JALISCO", "JALISCO": "JALISCO", "Jalisco": "JALISCO",
    "ME": "MEXICO", "MÉXICO": "MÉXICO", "México": "MÉXICO", "MEX": "MÉXICO",
    "MI": "MICHOACÁN", "MICHOACÁN": "MICHOACÁN", "Michoacán": "MICHOACÁN",
    "MO": "MORELOS", "MORELOS": "MORELOS", "Morelos": "MORELOS",
    "NA": "NAYARIT", "NAYARIT": "NAYARIT", "Nayarit": "NAYARIT",
    "NL": "NUEVO LEÓN", "NUEVO LEÓN": "NUEVO LEÓN", "Nuevo León": "NUEVO LEÓN",
    "OA": "OAXACA", "OAXACA": "OAXACA", "Oaxaca": "OAXACA",
    "PU": "PUEBLA", "PUEBLA": "PUEBLA", "Puebla": "PUEBLA",
    "QE": "QUERÉTARO", "QUERÉTARO": "QUERÉTARO", "Querétaro": "QUERÉTARO",
    "QR": "QUINTANA ROO", "QUINTANA ROO": "QUINTANA ROO", "Quintana Roo": "QUINTANA ROO",
    "SL": "SAN LUIS POTOSÍ", "SAN LUIS POTOSÍ": "SAN LUIS POTOSÍ", "San Luis Potosí": "SAN LUIS POTOSÍ",
    "SI": "SINALOA", "SINALOA": "SINALOA", "Sinaloa": "SINALOA",
    "SO": "SONORA", "SONORA": "SONORA", "Sonora": "SONORA",
    "TA": "TAMAULIPAS", "TAMAULIPAS": "TAMAULIPAS", "Tamaulipas": "TAMAULIPAS",
    "TL": "TLAXCALA", "TLAXCALA": "TLAXCALA", "Tlaxcala": "TLAXCALA",
    "VE": "VERACRUZ", "VERACRUZ": "VERACRUZ", "Veracruz": "VERACRUZ",
    "YU": "YUCATÁN", "YUCATÁN": "YUCATÁN", "Yucatán": "YUCATÁN",
    "ZA": "ZACATECAS", "ZACATECAS": "ZACATECAS", "Zacatecas": "ZACATECAS"
  };
  