/** @format */

import { createClient } from "@/utils/supabase/server";
import AuthButton from "@/components/AuthButton";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
import SideNavbar from "@/components/SideNavbar";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import signOut  from "./signOut.ts";
import Login from "./login/page";
const defaultUrl = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : "http://localhost:3000";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();


 
    
  
  return (
    <html lang="en">
      {!user ? (
        <body className="min-h-screen flex justify-center items-center ">
          {" "}
          <Login searchParams={{ message: "Inicie sesión para acceder al contenido protegido"}} />{" "}
        </body>
      ) : (
        <body
          className={cn(
            "min-h-screen w-full bg-white text-black flex ",
            inter.className,
            {
              "debug-screens": process.env.NODE_ENV === "development",
            }
          )}
        >
          {
           <SideNavbar signOut={signOut}  />
              
          
          }
          {/* main page */}
          <div className="p-8 w-full">
            {" "}
            <MantineProvider>
              {children}
            </MantineProvider>
          </div>
        </body>
      )}
    </html>
  );
}
